module.exports = exports = {
    "name": "{name}",
    "appname": "{appname}",
    "AppName": "{AppName}",
    "APPNAME": "{APPNAME}",
    "appdesc": "{appdesc} - generated by ezy-frontend platform",
    "apptitle": "{apptitle} - generated by ezy-frontend platform",
    "apppath": "{apppath}",
    "baseurl": "{baseurl}",
    "applogo": "/static/{appname}/images/logo.jpg",
    "version": "{version}",
    "template": "index.html",
    "port": {port},
    "socket_port": 10101,
    "livereload": {livereload}
}
