module.exports = exports = {
    "name": "demo",
    "appname": "demo",
    "AppName": "Demo",
    "APPNAME": "DEMO",
    "appdesc": "Demo - generated by ezy-frontend platform",
    "apptitle": "Demo - generated by ezy-frontend platform",
    "apppath": "/demo",
    "baseurl": "",
    "applogo": "/static/demo/images/logo.jpg",
    "version": "1.0.0",
    "template": "index.html",
    "port": 2810,
    "livereload": 1028
}
