module.exports = exports = {
    "appname": "{appname}",
    "AppName": "{AppName}",
    "APPNAME": "{APPNAME}",
    "appdesc": "{AppName} - generated by ezy-frontend platform",
    "apptitle": "{AppName} - generated by ezy-frontend platform",
    "apppath": "/",
    "applogo": "/{appname}/images/logo.jpg",
    "appversion": "0.0.1",
    "template": "index.html",
    "port": 2810,
    "livereload": 1028
}
