export default {
    "appname": "demo",
    "AppName": "demo",
    "APPNAME": "DEMO",
    "appdesc": "demo - generated by easy-frontend platform",
    "apptitle": "demo - generated by easy-frontend platform",
    "apppath": "/",
    "applogo": "/demo/images/logo.jpg",
    "appversion": "0.0.1",
    "template": "index.html",
    "port": 2810,
    "livereload": 1028
}
