import {config} from 'ezy/common'

export default config.set(
    {
        profile: 'uat',
        appname: 'demo',
        apppath: '//demo',
        AppName: 'Demo',
        APPNAME: 'DEMO',
        apptitle: 'Demo - generated by ezy-frontend platform',
        port: '2810',
        debug: true,
    },
    require('./base'),
    require('./uat'),
    typeof configuration != 'undefined' ? configuration : null
)
